import { createContext, useContext, useState, ReactNode } from "react";

type Language = "uzb" | "rus" | "eng" | "ara" | "zho" | "tur" | "deu";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  uzb: {
    // Header
    "header.home": "Bosh sahifa",
    "header.about": "Biz haqimizda",
    "header.partners": "Hamkorlarimiz",
    "header.services": "Xizmatlar",
    "header.results": "Natijalar",
    "header.contact": "Aloqa",
    "header.start": "Loyihani boshlash",
    
    // About
    "about.badge": "Biz haqimizda",
    "about.title": "Professional IT yechimlar bilan ishonchli hamkor",
    "about.subtitle": "Biz ATS - Automatic Technology Solutions - zamonaviy raqamli yechimlar yaratishga ixtisoslashgan kompaniyamiz. Bizning maqsadimiz - mijozlarimizning biznesini yangi texnologiyalar orqali rivojlantirish.",
    
    // Partners
    "partners.badge": "Bizning hamkorlarimiz",
    "partners.title": "Biz dunyoning turli burchaklarida ishlaymiz",
    "partners.subtitle": "Mintaqaviy va xalqaro hamkorlar bilan ishlaymiz. Har bir loyiha mahalliy xususiyatlar va global standartlarni hisobga oladi.",
    
    // Hero
    "hero.badge": "Innovatsiyalar va o'sish",
    "hero.title": "Biznesingiz",
    "hero.titleHighlight": "o'sishi",
    "hero.titleEnd": "uchun innovatsion IT-yechimlar",
    "hero.subtitle": "Raqamli marketing, fintex-ishlab chiqarish va e-commerce yechimlar orqali biznesingizni yangi bosqichga olib chiqamiz. Professionallik va innovatsiyalar birlashmasi.",
    "hero.consultation": "Bepul maslahat olish",
    "hero.viewServices": "Xizmatlarni ko'rish",
    "hero.clients": "Mijozlar",
    "hero.experience": "Yillik tajriba",
    "hero.support": "Qo'llab-quvvatlash",
    "hero.impressions": "Taassurotlar",
    "hero.engagement": "Jalb qilish darajasi",
    "hero.coverage": "Qamrov",
    "hero.buyers": "Onlayn xaridorlar",
    "hero.growth": "+20% o'sish",
    "hero.highResult": "Yuqori natija",
    "hero.wideAudience": "Keng auditoriya",
    "hero.digitalMarket": "Raqamli bozor",
    
    // Services
    "services.badge": "Bizning xizmatlarimiz",
    "services.title": "To'liq raqamli yechimlar sizning biznesingiz uchun",
    "services.subtitle": "Kichik va o'rta biznes uchun professional xizmatlar. Marketing, e-commerce va fintex sohasida zamonaviy yechimlar.",
    "services.marketing.title": "Raqamli marketing",
    "services.marketing.desc": "Ijtimoiy tarmoqlarda analitika, qamrovni oshirish va maqsadli auditoriyangizni jalb qilish. 2.86M qamrovga erishish mumkin.",
    "services.seo.title": "Mahalliy SEO",
    "services.seo.desc": "Yaqin atrofdagi mijozlarni jalb qiling. Kichik biznes uchun mahalliy qidiruvda yuqori o'rinlarni ta'minlaymiz.",
    "services.fintech.title": "Fintex-ishlab chiqarish",
    "services.fintech.desc": "Moliyaviy rejalashtirish uchun zamonaviy mobil ilovalar. Hisoblar va balanslarni bir bosishda boshqaring.",
    "services.ecommerce.title": "E-commerce yechimlar",
    "services.ecommerce.desc": "Onlayn-do'konlar uchun mobil ilovalar va veb platformalar. To'liq funksional va foydalanuvchilarga qulay interfeyslar.",
    "services.online.title": "Onlayn-kommersiya",
    "services.online.desc": "90% xaridorlar onlayn sotib oladi. Bizning yordam bilan raqamli savdoda ko'rinib turing va savdolarni oshiring.",
    "services.other.title": "Boshqa xizmatlar",
    "services.other.desc": "Sizning loyihangiz uchun maxsus yechimlar ishlab chiqamiz. Hoziroq bog'laning!",
    "services.other.button": "Bog'lanish",
    "services.detail": "Batafsil",
    
    // Why Us
    "whyus.badge": "Nega bizni tanlaysiz?",
    "whyus.title": "Biznesingiz muvaffaqiyati uchun ishonchli hamkor",
    "whyus.desc1": "Biz faqat xizmat ko'rsatmaymiz - biz sizning muvaffaqiyatingiz uchun sheriklik qilamiz. Har bir loyiha uchun individual yondashuv va zamonaviy texnologiyalar.",
    "whyus.desc2": "5+ yillik tajriba, 100+ mamnun mijozlar va minglab muvaffaqiyatli loyihalar - bu bizning professionalligimizning isboti.",
    "whyus.projects": "Bajarilgan loyihalar",
    "whyus.satisfaction": "Mijozlar mamnuniyati",
    "whyus.quality.title": "Yuqori sifat",
    "whyus.quality.desc": "Har bir loyiha professional darajada va eng yuqori standartlarda bajariladi.",
    "whyus.targeted.title": "Maqsadga yo'naltirilgan",
    "whyus.targeted.desc": "Sizning biznes maqsadlaringizni tushunamiz va ularga erishishda yordam beramiz.",
    "whyus.fast.title": "Tez ishlash",
    "whyus.fast.desc": "Loyihalarni o'z vaqtida va samarali tarzda topshiramiz, sifatni yo'qotmasdan.",
    "whyus.reliable.title": "Ishonchlilik",
    "whyus.reliable.desc": "Ma'lumotlaringiz xavfsizligi va maxfiyligi - bizning birinchi ustuvorligimiz.",
    "whyus.team.title": "Tajribali jamoa",
    "whyus.team.desc": "Professional mutaxassislar jamoasi har doim sizning xizmatingizda.",
    "whyus.support.title": "24/7 Qo'llab-quvvatlash",
    "whyus.support.desc": "Doimiy qo'llab-quvvatlash va tez javob berish kafolati.",
    
    // Portfolio
    "portfolio.badge": "Bizning ishlarimiz",
    "portfolio.title": "Muvaffaqiyatli loyihalar portfelimiz",
    "portfolio.subtitle": "Mijozlarimiz bilan birgalikda yaratgan ajoyib loyihalar. Har biri o'zining muvaffaqiyat tarixiga ega.",
    "portfolio.button": "Biz bilan loyiha boshlang",
    "portfolio.project1.title": "Marketing platformasi",
    "portfolio.project1.category": "Raqamli marketing",
    "portfolio.project1.description": "Ijtimoiy tarmoqlarda analitika va boshqaruv tizimi. Qamrovni 300% oshirish.",
    "portfolio.project1.stats": "2.5M+ foydalanuvchi",
    "portfolio.project2.title": "Fintex ilovasi",
    "portfolio.project2.category": "Fintech",
    "portfolio.project2.description": "Moliyaviy boshqaruv va rejalashtirish uchun mobil ilova. Bank darajasidagi xavfsizlik.",
    "portfolio.project2.stats": "500K+ yuklab olish",
    "portfolio.project3.title": "E-commerce do'kon",
    "portfolio.project3.category": "E-commerce",
    "portfolio.project3.description": "To'liq funksional onlayn-do'kon. Savdolarni 200% oshirish va konversiyani yaxshilash.",
    "portfolio.project3.stats": "$1M+ savdo",
    "portfolio.project4.title": "Startup ekotizimi",
    "portfolio.project4.category": "B2B Platform",
    "portfolio.project4.description": "Startaplar uchun kompleks boshqaruv tizimi. Jamoaviy ishlash va analytics.",
    "portfolio.project4.stats": "100+ kompaniya",
    "portfolio.project5.title": "CRM tizimi",
    "portfolio.project5.category": "Enterprise",
    "portfolio.project5.description": "Mijozlar bilan munosabatlarni boshqarish uchun kuchli vosita. AI integratsiyasi.",
    "portfolio.project5.stats": "10K+ foydalanuvchi",
    "portfolio.project6.title": "Tahlil platformasi",
    "portfolio.project6.category": "Analytics",
    "portfolio.project6.description": "Real-time biznes tahlil va prognozlash tizimi. Data-driven qarorlar uchun.",
    "portfolio.project6.stats": "50TB+ ma'lumot",
    
    // Stats
    "stats.badge": "Bizning natijalarimiz",
    "stats.title": "Raqamlar o'zi gapiradi",
    "stats.subtitle": "Mijozlarimiz uchun erishgan yutuqlar. Professional yondashuv va zamonaviy texnologiyalar natijasi.",
    "stats.growth": "O'sish so'nggi 6 oyda",
    "stats.clients": "Mamnun mijozlar",
    
    // Testimonials
    "testimonials.badge": "Mijozlar fikri",
    "testimonials.title": "Mijozlarimiz biz haqida nima deyishadi",
    "testimonials.subtitle": "Bizning eng katta maqtanishimiz - mamnun mijozlarimiz. Ularning fikrlari bizning sifatimizning eng yaxshi isboti.",
    "testimonials.rating": "O'rtacha reyting",
    "testimonials.reviews": "Sharhlar",
    "testimonials.recommend": "Tavsiya qiladi",
    "testimonials.years": "Yillik tajriba",
    "testimonials.testimonial1.name": "Jamshid Abdullayev",
    "testimonials.testimonial1.position": "Bosh direktor",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "ATS jamoasi bilan ishlash - bu ajoyib tajriba edi. Ular bizning biznesimizni haqiqatan ham tushunishdi va mukammal yechim yaratishdi. Savdolarimiz 200% oshdi!",
    "testimonials.testimonial2.name": "Dilnoza Karimova",
    "testimonials.testimonial2.position": "Marketing direktori",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "Professional yondashuv, zamonaviy texnologiyalar va ajoyib natijalar. Bizning marketing kampaniyamiz raqobatdan ancha oldinda turadi. Albatta tavsiya qilaman!",
    "testimonials.testimonial3.name": "Rustam Yusupov",
    "testimonials.testimonial3.position": "Asoschisi",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "Fintex ilovamizni ishlab chiqishda ATS bilan hamkorlik qilishdan juda mamnunmiz. Ular bizning g'oyalarimizni mukammal dasturga aylantirdilar. Professionallar!",
    "testimonials.testimonial4.name": "Nodira Rahimova",
    "testimonials.testimonial4.position": "Egasi",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "E-commerce platformamiz uchun ajoyib ish qilishdi. Sayt tez ishlaydi, chiroyli ko'rinadi va mijozlar uchun juda qulay. Xizmat ham a'lo darajada!",
    "testimonials.testimonial5.name": "Aziz Tursunov",
    "testimonials.testimonial5.position": "IT menejeri",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "Mahalliy SEO xizmatlari bizga juda ko'p yangi mijozlar keltirdi. Qidiruv natijalarida birinchi o'rinda turamiz. ATS - ishonchli hamkor!",
    "testimonials.testimonial6.name": "Shoxrux Mamadov",
    "testimonials.testimonial6.position": "Bosh direktor",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "CRM tizimimizni boshqarish hech qachon bunchalik oson bo'lmagan. ATS jamoasi bizning barcha talablarimizni inobatga oldi. Ajoyib natija!",
    
    // CTA
    "cta.badge": "Bog'lanish",
    "cta.title": "Loyihangizni bugun boshlang",
    "cta.subtitle": "Biznesingizni yangi bosqichga olib chiqishga tayyormisiz? Hoziroq bog'laning va bepul maslahat oling.",
    "cta.email": "Email",
    "cta.phone": "Telefon",
    "cta.address": "Manzil",
    "cta.addressValue": "Toshkent, O'zbekiston",
    "cta.name": "Ismingiz",
    "cta.namePlaceholder": "Ismingizni kiriting",
    "cta.emailLabel": "Email manzilingiz",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "Xabar",
    "cta.messagePlaceholder": "Loyihangiz haqida bizga ma'lumot bering...",
    "cta.submit": "Xabar yuborish",
    "cta.success": "Xabar muvaffaqiyatli yuborildi!",
    "cta.successMessage": "Tez orada siz bilan bog'lanamiz. Rahmat!",
    
    // Footer
    "footer.description": "Biznesingiz o'sishi uchun innovatsion IT-yechimlar. Raqamli marketing, fintex-ishlab chiqarish va e-commerce sohasida professional xizmatlar.",
    "footer.quickLinks": "Tezkor havolalar",
    "footer.services": "Xizmatlar",
    "footer.marketing": "Raqamli marketing",
    "footer.seo": "Mahalliy SEO",
    "footer.fintech": "Fintex-ishlab chiqarish",
    "footer.ecommerce": "E-commerce yechimlar",
    "footer.online": "Onlayn-kommersiya",
    "footer.copyright": "Automatic Technology Solutions. Barcha huquqlar himoyalangan.",
    "footer.privacy": "Maxfiylik siyosati",
    "footer.terms": "Foydalanish shartlari",
  },
  rus: {
    // Header
    "header.home": "Главная",
    "header.about": "О нас",
    "header.partners": "Наши партнёры",
    "header.services": "Услуги",
    "header.results": "Результаты",
    "header.contact": "Контакты",
    "header.start": "Начать проект",
    
    // About
    "about.badge": "О нас",
    "about.title": "Надежный партнер с профессиональными IT решениями",
    "about.subtitle": "Мы ATS - Automatic Technology Solutions - компания, специализирующаяся на создании современных цифровых решений. Наша цель - развивать бизнес наших клиентов через новые технологии.",
    
    // Partners
    "partners.badge": "Наши партнёры",
    "partners.title": "Мы работаем по всему миру",
    "partners.subtitle": "Сотрудничаем с региональными и международными партнёрами. Каждый проект учитывает местные особенности и глобальные стандарты.",
    
    // Hero
    "hero.badge": "Инновации и рост",
    "hero.title": "Инновационные IT-решения для",
    "hero.titleHighlight": "роста",
    "hero.titleEnd": "вашего бизнеса",
    "hero.subtitle": "Выведем ваш бизнес на новый уровень через цифровой маркетинг, финтех-разработку и e-commerce решения. Идеальное сочетание профессионализма и инноваций.",
    "hero.consultation": "Получить бесплатную консультацию",
    "hero.viewServices": "Посмотреть наши услуги",
    "hero.clients": "Клиентов",
    "hero.experience": "Лет опыта",
    "hero.support": "Поддержка",
    "hero.impressions": "Показов",
    "hero.engagement": "Уровень вовлеченности",
    "hero.coverage": "Охват",
    "hero.buyers": "Онлайн покупателей",
    "hero.growth": "+20% рост",
    "hero.highResult": "Высокая производительность",
    "hero.wideAudience": "Широкая аудитория",
    "hero.digitalMarket": "Цифровой рынок",
    
    // Services
    "services.badge": "Наши услуги",
    "services.title": "Полные цифровые решения для вашего бизнеса",
    "services.subtitle": "Профессиональные услуги для малого и среднего бизнеса. Современные решения в области маркетинга, e-commerce и финтех.",
    "services.marketing.title": "Цифровой маркетинг",
    "services.marketing.desc": "Аналитика в социальных сетях, увеличение охвата и привлечение целевой аудитории. Достигайте охвата до 2,86 млн пользователей.",
    "services.seo.title": "Локальное SEO",
    "services.seo.desc": "Привлекайте клиентов из вашего региона. Гарантируем высокие позиции в локальных результатах поиска для малого бизнеса.",
    "services.fintech.title": "Финтех-разработка",
    "services.fintech.desc": "Современные мобильные приложения для финансового планирования. Управляйте счетами и балансами одним кликом.",
    "services.ecommerce.title": "E-commerce решения",
    "services.ecommerce.desc": "Мобильные приложения и веб-платформы для интернет-магазинов. Полнофункциональные и удобные интерфейсы.",
    "services.online.title": "Онлайн-коммерция",
    "services.online.desc": "90% покупателей покупают онлайн. Выделитесь в цифровой торговле с нашей помощью и увеличьте продажи.",
    "services.other.title": "Другие услуги",
    "services.other.desc": "Разработаем индивидуальные решения под потребности вашего проекта. Свяжитесь прямо сейчас!",
    "services.other.button": "Связаться",
    "services.detail": "Подробнее",
    
    // Why Us
    "whyus.badge": "Почему выбирают нас?",
    "whyus.title": "Надежный партнер для успеха вашего бизнеса",
    "whyus.desc1": "Мы не просто оказываем услуги - мы становимся партнёрами для вашего успеха. Индивидуальный подход к каждому проекту и передовые технологии.",
    "whyus.desc2": "Более 5 лет опыта, свыше 100 довольных клиентов и тысячи успешных проектов - это доказательство нашего профессионализма.",
    "whyus.projects": "Выполненных проектов",
    "whyus.satisfaction": "Удовлетворенность клиентов",
    "whyus.quality.title": "Премиум качество",
    "whyus.quality.desc": "Каждый проект выполняется на профессиональном уровне по самым высоким отраслевым стандартам.",
    "whyus.targeted.title": "Целенаправленность",
    "whyus.targeted.desc": "Понимаем ваши бизнес-цели и эффективно помогаем их достичь.",
    "whyus.fast.title": "Быстрая доставка",
    "whyus.fast.desc": "Сдаем проекты вовремя и эффективно, не идя на компр��миссы с качеством.",
    "whyus.reliable.title": "Надежность",
    "whyus.reliable.desc": "Безопасность и конфиденциальность ваших данных - наш главный приоритет.",
    "whyus.team.title": "Команда экспертов",
    "whyus.team.desc": "Команда опытных профессионалов всегда к вашим услугам.",
    "whyus.support.title": "Поддержка 24/7",
    "whyus.support.desc": "Гарантированная непрерывная поддержка и быстрое время отклика.",
    
    // Portfolio
    "portfolio.badge": "Наше портфолио",
    "portfolio.title": "Портфолио успешных проектов",
    "portfolio.subtitle": "Выдающиеся проекты, созданные в сотрудничестве с нашими клиентами. У каждого своя уникальная история успеха.",
    "portfolio.button": "Начать свой проект с нами",
    "portfolio.project1.title": "Маркетинговая платформа",
    "portfolio.project1.category": "Цифровой маркетинг",
    "portfolio.project1.description": "Система аналитики и управления в социальных сетях. Увеличение охвата на 300%.",
    "portfolio.project1.stats": "2.5M+ пользователей",
    "portfolio.project2.title": "Финтех-приложение",
    "portfolio.project2.category": "Fintech",
    "portfolio.project2.description": "Мобильное приложение для финансового управления и планирования. Безопасность банковского уровня.",
    "portfolio.project2.stats": "500K+ загрузок",
    "portfolio.project3.title": "E-commerce магазин",
    "portfolio.project3.category": "E-commerce",
    "portfolio.project3.description": "Полнофункциональный интернет-магазин. Увеличение продаж на 200% и улучшение конверсии.",
    "portfolio.project3.stats": "$1M+ продаж",
    "portfolio.project4.title": "Стартап-экосистема",
    "portfolio.project4.category": "B2B Платформа",
    "portfolio.project4.description": "Комплексная система управления для стартапов. Командная работа и аналитика.",
    "portfolio.project4.stats": "100+ компаний",
    "portfolio.project5.title": "CRM система",
    "portfolio.project5.category": "Enterprise",
    "portfolio.project5.description": "Мощный инструмент для управления отношениями с клиентами. Интеграция с AI.",
    "portfolio.project5.stats": "10K+ пользователей",
    "portfolio.project6.title": "Аналитическая платформа",
    "portfolio.project6.category": "Analytics",
    "portfolio.project6.description": "Система анализа и прогнозирования бизнеса в реальном времени. Решения на основе данных.",
    "portfolio.project6.stats": "50TB+ данных",
    
    // Stats
    "stats.badge": "Наши результаты",
    "stats.title": "Цифры говорят сами за себя",
    "stats.subtitle": "Достижения, полученные для наших клиентов. Результат профессионального подхода и современных технологий.",
    "stats.growth": "Рост за последние 6 месяцев",
    "stats.clients": "Довольных клиентов",
    
    // Testimonials
    "testimonials.badge": "Отзывы клиентов",
    "testimonials.title": "Что говорят наши клиенты о нас",
    "testimonials.subtitle": "Наша главная гордость - довольные клиенты. Их отзывы - лучшее доказательство нашего качества.",
    "testimonials.rating": "Средний рейтинг",
    "testimonials.reviews": "Отзывов",
    "testimonials.recommend": "Порекомендуют нас",
    "testimonials.years": "Лет опыта",
    "testimonials.testimonial1.name": "Джамшид Абдуллаев",
    "testimonials.testimonial1.position": "Генеральный директор",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "Работа с командой ATS - это потрясающий опыт. Они действительно понимают наш бизнес и создали идеальное решение. Наши продажи выросли на 200%!",
    "testimonials.testimonial2.name": "Дильноза Каримова",
    "testimonials.testimonial2.position": "Директор по маркетингу",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "Профессиональный подход, современные технологии и отличные результаты. Наша маркетинговая кампания значительно опережает конкурентов. Определенно рекомендую!",
    "testimonials.testimonial3.name": "Рустам Юсупов",
    "testimonials.testimonial3.position": "Основатель",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "Мы очень довольны сотрудничеством с ATS в разработке нашего финтех-приложения. Они превратили наши идеи в превосходное приложение. Профессионалы!",
    "testimonials.testimonial4.name": "Нодира Рахимова",
    "testimonials.testimonial4.position": "Владелец",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "Проделали отличную работу для нашей e-commerce платформы. Сайт работает быстро, выглядит красиво и очень удобен для клиентов. Сервис на высшем уровне!",
    "testimonials.testimonial5.name": "Азиз Турсунов",
    "testimonials.testimonial5.position": "IT-менеджер",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "Услуги локального SEO привлекли нам очень много новых клиентов. Мы на первом месте в результатах поиска. ATS - надежный партнер!",
    "testimonials.testimonial6.name": "Шохрух Мамадов",
    "testimonials.testimonial6.position": "Генеральный директор",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "Управление нашей CRM системой никогда не было таким простым. Команда ATS учла все наши требования. Превосходный результат!",
    
    // CTA
    "cta.badge": "Свяжитесь с нами",
    "cta.title": "Начните ваш проект сегодня",
    "cta.subtitle": "Готовы вывести свой бизнес на новый уровень? Свяжитесь с нами прямо сейчас и получите бесплатную консультацию.",
    "cta.email": "Email",
    "cta.phone": "Телефон",
    "cta.address": "Адрес",
    "cta.addressValue": "Ташкент, Узбекистан",
    "cta.name": "Ваше имя",
    "cta.namePlaceholder": "Введите ваше имя",
    "cta.emailLabel": "Ваш email",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "Сообщение",
    "cta.messagePlaceholder": "Расскажите нам о вашем проекте...",
    "cta.submit": "Отправить сообщение",
    "cta.success": "Сообщение успешно отправлено!",
    "cta.successMessage": "Мы скоро свяжемся с вами. Спасибо!",
    
    // Footer
    "footer.description": "Инновационные IT-решения для роста вашего бизнеса. Профессиональные услуги в области цифрового маркетинга, финтех-разработки и e-commerce.",
    "footer.quickLinks": "Быстрые ссылки",
    "footer.services": "Услуги",
    "footer.marketing": "Цифровой маркетинг",
    "footer.seo": "Локальное SEO",
    "footer.fintech": "Финтех-разработка",
    "footer.ecommerce": "E-commerce решения",
    "footer.online": "Онлайн-коммерция",
    "footer.copyright": "Automatic Technology Solutions. Все права защищены.",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия использования",
  },
  eng: {
    // Header
    "header.home": "Home",
    "header.about": "About Us",
    "header.partners": "Our Partners",
    "header.services": "Services",
    "header.results": "Results",
    "header.contact": "Contact",
    "header.start": "Start Project",
    
    // About
    "about.badge": "About Us",
    "about.title": "Trusted Partner with Professional IT Solutions",
    "about.subtitle": "We are ATS - Automatic Technology Solutions - a company specializing in creating modern digital solutions. Our goal is to develop our clients' business through new technologies.",
    
    // Partners
    "partners.badge": "Our Partners",
    "partners.title": "We Work Worldwide",
    "partners.subtitle": "We collaborate with regional and international partners. Each project takes into account local specifics and global standards.",
    
    // Hero
    "hero.badge": "Innovation & Growth",
    "hero.title": "Innovative IT Solutions for Your Business",
    "hero.titleHighlight": "Growth",
    "hero.titleEnd": "",
    "hero.subtitle": "We take your business to the next level through digital marketing, fintech development, and e-commerce solutions. A perfect blend of professionalism and innovation.",
    "hero.consultation": "Get Free Consultation",
    "hero.viewServices": "View Our Services",
    "hero.clients": "Clients",
    "hero.experience": "Years of Experience",
    "hero.support": "Support",
    "hero.impressions": "Impressions",
    "hero.engagement": "Engagement Rate",
    "hero.coverage": "Reach",
    "hero.buyers": "Online Buyers",
    "hero.growth": "+20% Growth",
    "hero.highResult": "High Performance",
    "hero.wideAudience": "Wide Audience",
    "hero.digitalMarket": "Digital Market",
    
    // Services
    "services.badge": "Our Services",
    "services.title": "Complete Digital Solutions for Your Business",
    "services.subtitle": "Professional services for small and medium-sized businesses. Modern solutions in marketing, e-commerce, and fintech.",
    "services.marketing.title": "Digital Marketing",
    "services.marketing.desc": "Social media analytics, reach expansion, and target audience engagement. Achieve reach of up to 2.86M users.",
    "services.seo.title": "Local SEO",
    "services.seo.desc": "Attract customers from your local area. We ensure high rankings in local search results for small businesses.",
    "services.fintech.title": "Fintech Development",
    "services.fintech.desc": "Modern mobile applications for financial planning. Manage accounts and balances with a single click.",
    "services.ecommerce.title": "E-Commerce Solutions",
    "services.ecommerce.desc": "Mobile apps and web platforms for online stores. Fully functional and user-friendly interfaces.",
    "services.online.title": "Online Commerce",
    "services.online.desc": "90% of buyers shop online. Stand out in digital commerce with our help and boost your sales.",
    "services.other.title": "Other Services",
    "services.other.desc": "We develop custom solutions tailored to your project needs. Contact us today!",
    "services.other.button": "Contact Us",
    "services.detail": "Learn More",
    
    // Why Us
    "whyus.badge": "Why Choose Us?",
    "whyus.title": "Your Reliable Partner for Business Success",
    "whyus.desc1": "We don't just provide services - we become your partners in success. Individual approach to every project combined with cutting-edge technologies.",
    "whyus.desc2": "Over 5 years of experience, more than 100 satisfied clients, and thousands of successful projects - this is proof of our professionalism.",
    "whyus.projects": "Completed Projects",
    "whyus.satisfaction": "Client Satisfaction",
    "whyus.quality.title": "Premium Quality",
    "whyus.quality.desc": "Every project is executed at a professional level according to the highest industry standards.",
    "whyus.targeted.title": "Goal-Oriented",
    "whyus.targeted.desc": "We understand your business objectives and help you achieve them effectively.",
    "whyus.fast.title": "Fast Delivery",
    "whyus.fast.desc": "We deliver projects on time and efficiently without compromising on quality.",
    "whyus.reliable.title": "Reliability",
    "whyus.reliable.desc": "Security and confidentiality of your data is our top priority.",
    "whyus.team.title": "Expert Team",
    "whyus.team.desc": "A team of seasoned professionals always at your service.",
    "whyus.support.title": "24/7 Support",
    "whyus.support.desc": "Guaranteed continuous support and rapid response times.",
    
    // Portfolio
    "portfolio.badge": "Our Portfolio",
    "portfolio.title": "Successful Project Portfolio",
    "portfolio.subtitle": "Outstanding projects created in collaboration with our clients. Each one has its own unique success story.",
    "portfolio.button": "Start Your Project With Us",
    "portfolio.project1.title": "Marketing Platform",
    "portfolio.project1.category": "Digital Marketing",
    "portfolio.project1.description": "Social media analytics and management system. 300% increase in reach.",
    "portfolio.project1.stats": "2.5M+ Users",
    "portfolio.project2.title": "Fintech Application",
    "portfolio.project2.category": "Fintech",
    "portfolio.project2.description": "Mobile app for financial management and planning. Bank-level security.",
    "portfolio.project2.stats": "500K+ Downloads",
    "portfolio.project3.title": "E-commerce Store",
    "portfolio.project3.category": "E-commerce",
    "portfolio.project3.description": "Fully functional online store. 200% sales increase and improved conversion.",
    "portfolio.project3.stats": "$1M+ Sales",
    "portfolio.project4.title": "Startup Ecosystem",
    "portfolio.project4.category": "B2B Platform",
    "portfolio.project4.description": "Complex management system for startups. Team collaboration and analytics.",
    "portfolio.project4.stats": "100+ Companies",
    "portfolio.project5.title": "CRM System",
    "portfolio.project5.category": "Enterprise",
    "portfolio.project5.description": "Powerful tool for customer relationship management. AI integration.",
    "portfolio.project5.stats": "10K+ Users",
    "portfolio.project6.title": "Analytics Platform",
    "portfolio.project6.category": "Analytics",
    "portfolio.project6.description": "Real-time business analysis and forecasting system. Data-driven decisions.",
    "portfolio.project6.stats": "50TB+ Data",
    
    // Stats
    "stats.badge": "Our Results",
    "stats.title": "Numbers Speak for Themselves",
    "stats.subtitle": "Achievements delivered for our clients. The result of professional approach and modern technologies.",
    "stats.growth": "Growth Over Last 6 Months",
    "stats.clients": "Satisfied Clients",
    
    // Testimonials
    "testimonials.badge": "Client Testimonials",
    "testimonials.title": "What Our Clients Say About Us",
    "testimonials.subtitle": "Our greatest pride is our satisfied clients. Their testimonials are the best proof of our quality.",
    "testimonials.rating": "Average Rating",
    "testimonials.reviews": "Reviews",
    "testimonials.recommend": "Would Recommend",
    "testimonials.years": "Years of Experience",
    "testimonials.testimonial1.name": "Jamshid Abdullayev",
    "testimonials.testimonial1.position": "CEO",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "Working with the ATS team was an amazing experience. They truly understood our business and created the perfect solution. Our sales increased by 200%!",
    "testimonials.testimonial2.name": "Dilnoza Karimova",
    "testimonials.testimonial2.position": "Marketing Director",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "Professional approach, modern technologies, and excellent results. Our marketing campaign is far ahead of the competition. Definitely recommend!",
    "testimonials.testimonial3.name": "Rustam Yusupov",
    "testimonials.testimonial3.position": "Founder",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "We are very pleased with our collaboration with ATS on developing our fintech app. They turned our ideas into an excellent application. True professionals!",
    "testimonials.testimonial4.name": "Nodira Rahimova",
    "testimonials.testimonial4.position": "Owner",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "They did an excellent job for our e-commerce platform. The site runs fast, looks beautiful, and is very convenient for customers. Service is top-notch!",
    "testimonials.testimonial5.name": "Aziz Tursunov",
    "testimonials.testimonial5.position": "IT Manager",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "Local SEO services brought us a lot of new customers. We rank first in search results. ATS is a reliable partner!",
    "testimonials.testimonial6.name": "Shoxrux Mamadov",
    "testimonials.testimonial6.position": "CEO",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "Managing our CRM system has never been easier. The ATS team took all our requirements into account. Excellent result!",
    
    // CTA
    "cta.badge": "Get in Touch",
    "cta.title": "Start Your Project Today",
    "cta.subtitle": "Ready to take your business to the next level? Contact us now and receive a free consultation.",
    "cta.email": "Email",
    "cta.phone": "Phone",
    "cta.address": "Address",
    "cta.addressValue": "Tashkent, Uzbekistan",
    "cta.name": "Your Name",
    "cta.namePlaceholder": "Enter your name",
    "cta.emailLabel": "Your Email",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "Message",
    "cta.messagePlaceholder": "Tell us about your project...",
    "cta.submit": "Send Message",
    "cta.success": "Message Sent Successfully!",
    "cta.successMessage": "We will contact you shortly. Thank you!",
    
    // Footer
    "footer.description": "Innovative IT solutions for your business growth. Professional services in digital marketing, fintech development, and e-commerce.",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.marketing": "Digital Marketing",
    "footer.seo": "Local SEO",
    "footer.fintech": "Fintech Development",
    "footer.ecommerce": "E-Commerce Solutions",
    "footer.online": "Online Commerce",
    "footer.copyright": "Automatic Technology Solutions. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },
  ara: {
    // Header
    "header.home": "الرئيسية",
    "header.about": "من نحن",
    "header.partners": "شركاؤنا",
    "header.services": "خدماتنا",
    "header.results": "النتائج",
    "header.contact": "تواصل معنا",
    "header.start": "ابدأ مشروعك",
    
    // About
    "about.badge": "من نحن",
    "about.title": "شريك موثوق مع حلول تقنية محترفة",
    "about.subtitle": "نحن ATS - Automatic Technology Solutions - شركة متخصصة في إنشاء الحلول الرقمية الحديثة. هدفنا هو تطوير أعمال عملائنا من خلال التقنيات الجديدة.",
    
    // Partners
    "partners.badge": "شركاؤنا",
    "partners.title": "نعمل في جميع أنحاء العالم",
    "partners.subtitle": "نتعاون مع الشركاء الإقليميين والدوليين. يأخذ كل مشروع في الاعتبار الخصائص المحلية والمعايير العالمية.",
    
    // Hero
    "hero.badge": "الابتكار والنمو",
    "hero.title": "حلول تقنية معلومات مبتكرة",
    "hero.titleHighlight": "لنمو",
    "hero.titleEnd": "أعمالك",
    "hero.subtitle": "نرتقي بأعمالك إلى المستوى التالي من خلال التسويق الرقمي، تطوير ��لتكنولوجيا المالية وحلول التجارة الإلكترونية. مزيج مثالي من الاحترافية والابتكار.",
    "hero.consultation": "احصل على استشارة مجانية",
    "hero.viewServices": "استعرض خدماتنا",
    "hero.clients": "عميل",
    "hero.experience": "سنوات من الخبرة",
    "hero.support": "دعم فني",
    "hero.impressions": "مشاهدة",
    "hero.engagement": "معدل التفاعل",
    "hero.coverage": "الوصول",
    "hero.buyers": "مشتري عبر الإنترنت",
    "hero.growth": "نمو +20%",
    "hero.highResult": "أداء عالي",
    "hero.wideAudience": "جمهور واسع",
    "hero.digitalMarket": "السوق الرقمي",
    
    // Services
    "services.badge": "خدماتنا",
    "services.title": "حلول رقمية متكاملة لأعمالك",
    "services.subtitle": "خدمات احترافية للشركات الصغيرة والمتوسطة. حلول عصرية في التسويق، التجارة الإلكترونية والتكنولوجيا المالية.",
    "services.marketing.title": "التسويق الرقمي",
    "services.marketing.desc": "تحليلات وسائل التواصل الاجتماعي، توسيع نطاق الوصول وجذب الجمهور المستهدف. حقق وصولاً يصل إلى 2.86 مليون مستخدم.",
    "services.seo.title": "تحسين محركات البحث المحلية",
    "services.seo.desc": "اجذب العملاء من منطقتك المحلية. نضمن ترتيباً عالياً في نتائج البحث المحلية للشركات الصغيرة.",
    "services.fintech.title": "تطوير التكنولوجيا المالية",
    "services.fintech.desc": "تطبيقات جوال عصرية للتخطيط المالي. إدارة الحسابات والأرصدة بنقرة واحدة.",
    "services.ecommerce.title": "حلول التجارة الإلكترونية",
    "services.ecommerce.desc": "تطبيقات جوال ومنصات ويب للمتاجر الإلكترونية. واجهات كاملة الوظائف وسهلة الاستخدام.",
    "services.online.title": "التجارة الإلكترونية",
    "services.online.desc": "90% من المشترين يتسوقون عبر الإنترنت. تميز في التجارة الرقمية بمساعدتنا وعزز مبيعاتك.",
    "services.other.title": "خدمات أخرى",
    "services.other.desc": "نطور حلولاً مخصصة تناسب احتياجات مشروعك. تواصل معنا اليوم!",
    "services.other.button": "تواصل معنا",
    "services.detail": "اعرف المزيد",
    
    // Why Us
    "whyus.badge": "لماذا تختارنا؟",
    "whyus.title": "شريكك الموثوق لنجاح الأعمال",
    "whyus.desc1": "نحن لا نقدم الخدمات فقط - بل نصبح شركاء في نجاحك. نهج فردي لكل مشروع مع تقنيات متطورة.",
    "whyus.desc2": "أكثر من 5 سنوات من الخبرة، أكثر من 100 عميل راضٍ، وآلاف المشاريع الناجحة - هذا دليل على احترافيتنا.",
    "whyus.projects": "مشروع منجز",
    "whyus.satisfaction": "رضا العملاء",
    "whyus.quality.title": "جودة عالية",
    "whyus.quality.desc": "يتم تنفيذ كل مشروع على مستوى احترافي وفقاً لأعلى معايير الصناعة.",
    "whyus.targeted.title": "موجه نحو الهدف",
    "whyus.targeted.desc": "نفهم أهداف أعمالك ونساعدك على تحقيقها بفعالية.",
    "whyus.fast.title": "تسليم سريع",
    "whyus.fast.desc": "نسلم المشاريع في الوقت المحدد وبكفاءة دون المساس بالجودة.",
    "whyus.reliable.title": "الموثوقية",
    "whyus.reliable.desc": "أمان وسرية بياناتك هو أولويتنا القصوى.",
    "whyus.team.title": "فريق خبراء",
    "whyus.team.desc": "فريق من المحترفين المتمرسين دائماً في خدمتك.",
    "whyus.support.title": "دعم على مدار الساعة",
    "whyus.support.desc": "دعم مستمر مضمون وأوقات استجابة سريعة.",
    
    // Portfolio
    "portfolio.badge": "أعمالنا",
    "portfolio.title": "محفظة المشاريع الناجحة",
    "portfolio.subtitle": "مشاريع متميزة تم إنشاؤها بالتعاون مع عملائنا. كل منها له قصة نجاح فريدة.",
    "portfolio.button": "ابدأ مشروعك معنا",
    "portfolio.project1.title": "منصة التسويق",
    "portfolio.project1.category": "التسويق الرقمي",
    "portfolio.project1.description": "نظام تحليل وإدارة وسائل التواصل الاجتماعي. زيادة الوصول بنسبة 300%.",
    "portfolio.project1.stats": "2.5 مليون+ مستخدم",
    "portfolio.project2.title": "تطبيق التكنولوجيا المالية",
    "portfolio.project2.category": "التكنولوجيا المالية",
    "portfolio.project2.description": "تطبيق جوال للإدارة والتخطيط المالي. أمان بمستوى البنوك.",
    "portfolio.project2.stats": "500 ألف+ تنزيل",
    "portfolio.project3.title": "متجر إلكتروني",
    "portfolio.project3.category": "التجارة الإلكترونية",
    "portfolio.project3.description": "متجر إلكتروني متكامل الوظائف. زيادة المبيعات بنسبة 200% وتحسين معدل التحويل.",
    "portfolio.project3.stats": "1 مليون$+ مبيعات",
    "portfolio.project4.title": "نظام بيئة الشركات الناشئة",
    "portfolio.project4.category": "منصة B2B",
    "portfolio.project4.description": "نظام إدارة معقد للشركات الناشئة. التعاون الجماعي والتحليلات.",
    "portfolio.project4.stats": "100+ شركة",
    "portfolio.project5.title": "نظام CRM",
    "portfolio.project5.category": "مؤسسات",
    "portfolio.project5.description": "أداة قوية لإدارة علاقات العملاء. تكامل الذكاء الاصطناعي.",
    "portfolio.project5.stats": "10 آلاف+ مستخدم",
    "portfolio.project6.title": "منصة التحليلات",
    "portfolio.project6.category": "التحليلات",
    "portfolio.project6.description": "نظام تحليل وتوقعات الأعمال في الوقت الفعلي. قرارات مدفوعة بالبيانات.",
    "portfolio.project6.stats": "50 تيرابايت+ بيانات",
    
    // Stats
    "stats.badge": "نتائجنا",
    "stats.title": "الأرقام تتحدث عن نفسها",
    "stats.subtitle": "إنجازات محققة لعملائنا. نتيجة النهج الاحترافي والتقنيات الحديثة.",
    "stats.growth": "النمو خلال آخر 6 أشهر",
    "stats.clients": "عميل راضٍ",
    
    // Testimonials
    "testimonials.badge": "آراء العملاء",
    "testimonials.title": "ماذا يقول عملاؤنا عنا",
    "testimonials.subtitle": "فخرنا الأكبر هو عملاؤنا الراضون. شهاداتهم هي أفضل دليل على جودتنا.",
    "testimonials.rating": "متوسط التقييم",
    "testimonials.reviews": "تقييم",
    "testimonials.recommend": "يوصون بنا",
    "testimonials.years": "سنوات من الخبرة",
    "testimonials.testimonial1.name": "جمشيد عبد الله",
    "testimonials.testimonial1.position": "الرئيس التنفيذي",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "العمل مع فريق ATS كان تجربة رائعة. لقد فهموا أعمالنا حقاً وأنشأوا الحل المثالي. زادت مبيعاتنا بنسبة 200%!",
    "testimonials.testimonial2.name": "دلنوزا كريموفا",
    "testimonials.testimonial2.position": "مديرة التسويق",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "نهج احترافي، تقنيات حديثة، ونتائج ممتازة. حملتنا التسويقية متقدمة جداً على المنافسين. بالتأكيد أوصي!",
    "testimonials.testimonial3.name": "رستم يوسفوف",
    "testimonials.testimonial3.position": "المؤسس",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "نحن سعداء جداً بتعاوننا مع ATS في تطوير تطبيق التكنولوجيا المالية. حولوا أفكارنا إلى تطبيق ممتاز. محترفون حقيقيون!",
    "testimonials.testimonial4.name": "نديرة رحيموفا",
    "testimonials.testimonial4.position": "المالكة",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "قاموا بعمل ممتاز لمنصة التجارة الإلكترونية لدينا. الموقع يعمل بسرعة، يبدو جميلاً، ومريح جداً للعملاء. الخدمة من الدرجة الأولى!",
    "testimonials.testimonial5.name": "عزيز تورسونوف",
    "testimonials.testimonial5.position": "مدير تقنية المعلومات",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "خدمات تحسين محركات البحث المحلية جلبت لنا الكثير من العملاء الجدد. نحن في المرتبة الأولى في نتائج البحث. ATS شريك موثوق!",
    "testimonials.testimonial6.name": "شخروخ مامادوف",
    "testimonials.testimonial6.position": "الرئيس التنفيذي",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "إدارة نظام CRM لم تكن أسهل من أي وقت مضى. أخذ فريق ATS جميع متطلباتنا في الاعتبار. نتيجة ممتازة!",
    
    // CTA
    "cta.badge": "تواصل معنا",
    "cta.title": "ابدأ مشروعك اليوم",
    "cta.subtitle": "هل أنت مستعد لنقل أعمالك إلى المستوى التالي؟ تواصل معنا الآن واحصل على استشارة مجانية.",
    "cta.email": "البريد الإلكتروني",
    "cta.phone": "الهاتف",
    "cta.address": "العنوان",
    "cta.addressValue": "طشقند، أوزبكستان",
    "cta.name": "اسمك",
    "cta.namePlaceholder": "أدخل اسمك",
    "cta.emailLabel": "بريدك الإلكتروني",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "الرسالة",
    "cta.messagePlaceholder": "أخبرنا عن مشروعك...",
    "cta.submit": "إرسال الرسالة",
    "cta.success": "تم إرسال الرسالة بنجاح!",
    "cta.successMessage": "سنتواصل معك قريباً. شكراً لك!",
    
    // Footer
    "footer.description": "حلول تقنية معلومات مبتكرة لنمو أعمالك. خدمات احترافية في التسويق الرقمي، تطوير التكنولوجيا المالية والتجارة الإلكترونية.",
    "footer.quickLinks": "روابط سريعة",
    "footer.services": "الخدمات",
    "footer.marketing": "التسويق الرقمي",
    "footer.seo": "تحسين محركات البحث المحلية",
    "footer.fintech": "تطوير التكنولوجيا المالية",
    "footer.ecommerce": "حلول التجارة الإلكترونية",
    "footer.online": "التجارة الإلكترونية",
    "footer.copyright": "Automatic Technology Solutions. جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
  },
  zho: {
    // Header
    "header.home": "首页",
    "header.about": "关于我们",
    "header.partners": "我们的合作伙伴",
    "header.services": "服务项目",
    "header.results": "成果展示",
    "header.contact": "联系我们",
    "header.start": "启动项目",
    
    // About
    "about.badge": "关于我们",
    "about.title": "值得信赖的专业IT解决方案合作伙伴",
    "about.subtitle": "我们是ATS - Automatic Technology Solutions - 一家专门创建现代数字解决方案的公司。我们的目标是通过新技术发展客户的业务。",
    
    // Partners
    "partners.badge": "我们的合作伙伴",
    "partners.title": "我们在全球范围内工作",
    "partners.subtitle": "我们与区域和国际合作伙伴合作。每个项目都考虑当地特点和全球标准。",
    
    // Hero
    "hero.badge": "创新与增长",
    "hero.title": "为您的企业提供创新IT解决方案",
    "hero.titleHighlight": "增长",
    "hero.titleEnd": "",
    "hero.subtitle": "通过数字营销、金融科技开发和电子商务解决方案，将您的业务提升到新的高度。专业与创新的完美结合。",
    "hero.consultation": "获取免费咨询",
    "hero.viewServices": "查看我们的服务",
    "hero.clients": "客户",
    "hero.experience": "年行业经验",
    "hero.support": "技术支持",
    "hero.impressions": "展示次数",
    "hero.engagement": "参与率",
    "hero.coverage": "覆盖范围",
    "hero.buyers": "在线买家",
    "hero.growth": "+20% 增长",
    "hero.highResult": "高性能",
    "hero.wideAudience": "广泛受众",
    "hero.digitalMarket": "数字市场",
    
    // Services
    "services.badge": "我们的服务",
    "services.title": "为您的企业提供完整的数字化解决方案",
    "services.subtitle": "为中小企业提供专业服务。在营销、电子商务和金融科技领域提供现代化解决方案。",
    "services.marketing.title": "数字营销",
    "services.marketing.desc": "社交媒体分析、扩大覆盖范围和目标受众参与。实现高达286万用户的覆盖范围。",
    "services.seo.title": "本地SEO优化",
    "services.seo.desc": "吸引您当地的客户。我们确保小企业在本地搜索结果中获得高排名。",
    "services.fintech.title": "金融科技开发",
    "services.fintech.desc": "用于财务规划的现代移动应用程序。一键管理账户和余额。",
    "services.ecommerce.title": "电子商务解决方案",
    "services.ecommerce.desc": "为在线商店提供移动应用和网络平台。功能齐全且用户友好的界面。",
    "services.online.title": "在线商务",
    "services.online.desc": "90%的买家在线购物。借助我们的帮助在数字商务中脱颖而出，提升您的销售额。",
    "services.other.title": "其他服务",
    "services.other.desc": "我们为您的项目需求开发定制解决方案。立即联系我们！",
    "services.other.button": "联系我们",
    "services.detail": "了解更多",
    
    // Why Us
    "whyus.badge": "为什么选择我们？",
    "whyus.title": "您企业成功的可靠合作伙伴",
    "whyus.desc1": "我们不仅提供服务 - 我们成为您成功的合作伙伴。结合尖端技术，为每个项目提供个性化方案。",
    "whyus.desc2": "超过5年的经验、100多个满意的客户和数千个成功的项目 - 这证明了我们的专业性。",
    "whyus.projects": "完成项目",
    "whyus.satisfaction": "客户满意度",
    "whyus.quality.title": "卓越品质",
    "whyus.quality.desc": "每个项目都按照行业最高标准在专业水平上执行。",
    "whyus.targeted.title": "目标明确",
    "whyus.targeted.desc": "我们了解您的业务目标，并有效地帮助您实现它们。",
    "whyus.fast.title": "快速交付",
    "whyus.fast.desc": "我们按时高效地交付项目，不影响质量。",
    "whyus.reliable.title": "可靠性",
    "whyus.reliable.desc": "您数据的安全和保密是我们的首要任务。",
    "whyus.team.title": "专家团队",
    "whyus.team.desc": "经验丰富的专业团队随时为您服务。",
    "whyus.support.title": "全天候支持",
    "whyus.support.desc": "保证持续支持和快速响应时间。",
    
    // Portfolio
    "portfolio.badge": "我们的作品",
    "portfolio.title": "成功项目作品集",
    "portfolio.subtitle": "与我们的客户合作创建的杰出项目。每个项目都有其独特的成功故事。",
    "portfolio.button": "与我们一起开始您的项目",
    "portfolio.project1.title": "营销平台",
    "portfolio.project1.category": "数字营销",
    "portfolio.project1.description": "社交媒体分析和管理系统。覆盖范围增长300%。",
    "portfolio.project1.stats": "250万+ 用户",
    "portfolio.project2.title": "金融科技应用",
    "portfolio.project2.category": "金融科技",
    "portfolio.project2.description": "财务管理和规划移动应用程序。银行级安全性。",
    "portfolio.project2.stats": "50万+ 下载",
    "portfolio.project3.title": "电子商务商店",
    "portfolio.project3.category": "电子商务",
    "portfolio.project3.description": "全功能在线商店。销售额增长200%，转化率提升。",
    "portfolio.project3.stats": "100万$+ 销售额",
    "portfolio.project4.title": "创业生态系统",
    "portfolio.project4.category": "B2B平台",
    "portfolio.project4.description": "初创企业复杂管理系统。团队协作和分析。",
    "portfolio.project4.stats": "100+ 公司",
    "portfolio.project5.title": "CRM系统",
    "portfolio.project5.category": "企业级",
    "portfolio.project5.description": "客户关系管理强大工具。AI集成。",
    "portfolio.project5.stats": "1万+ 用户",
    "portfolio.project6.title": "分析平台",
    "portfolio.project6.category": "数据分析",
    "portfolio.project6.description": "实时业务分析和预测系统。数据驱动决策。",
    "portfolio.project6.stats": "50TB+ 数据",
    
    // Stats
    "stats.badge": "我们的成果",
    "stats.title": "数字说明一切",
    "stats.subtitle": "为我们的客户实现的成就。专业方法和现代技术的成果。",
    "stats.growth": "过去6个月的增长",
    "stats.clients": "满意客户",
    
    // Testimonials
    "testimonials.badge": "客户评价",
    "testimonials.title": "客户对我们的评价",
    "testimonials.subtitle": "我们最大的骄傲是我们满意的客户。他们的评价是我们质量的最佳证明。",
    "testimonials.rating": "平均评分",
    "testimonials.reviews": "条评价",
    "testimonials.recommend": "愿意推荐",
    "testimonials.years": "年行业经验",
    "testimonials.testimonial1.name": "贾姆希德·阿卜杜拉耶夫",
    "testimonials.testimonial1.position": "首席执行官",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "与ATS团队合作是一次美妙的体验。他们真正理解我们的业务并创建了完美的解决方案。我们的销售额增长了200%！",
    "testimonials.testimonial2.name": "迪尔诺扎·卡里莫娃",
    "testimonials.testimonial2.position": "营销总监",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "专业的方法、现代技术和卓越的成果。我们的营销活动远远领先于竞争对手。绝对推荐！",
    "testimonials.testimonial3.name": "鲁斯塔姆·尤苏波夫",
    "testimonials.testimonial3.position": "创始人",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "我们非常满意与ATS合作开发我们的金融科技应用。他们将我们的想法变成了出色的应用程序。真正的专业人士！",
    "testimonials.testimonial4.name": "诺迪拉·拉希莫娃",
    "testimonials.testimonial4.position": "所有者",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "他们为我们的电子商务平台做了出色的工作。网站运行速度快、外观美观，对客户非常方便。服务一流！",
    "testimonials.testimonial5.name": "阿齐兹·图尔苏诺夫",
    "testimonials.testimonial5.position": "IT经理",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "本地SEO服务为我们带来了很多新客户。我们在搜索结果中排名第一。ATS是可靠的合作伙伴！",
    "testimonials.testimonial6.name": "肖赫鲁赫·马马多夫",
    "testimonials.testimonial6.position": "首席执行官",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "管理我们的CRM系统从未如此简单。ATS团队考虑了我们所有的要求。出色的结果！",
    
    // CTA
    "cta.badge": "联系我们",
    "cta.title": "今天就开始您的项目",
    "cta.subtitle": "准备好将您的业务提升到新的水平了吗？立即联系我们，获得免费咨询。",
    "cta.email": "电子邮箱",
    "cta.phone": "联系电话",
    "cta.address": "地址",
    "cta.addressValue": "乌兹别克斯坦，塔什干",
    "cta.name": "您的姓名",
    "cta.namePlaceholder": "请输入您的姓名",
    "cta.emailLabel": "您的电子邮箱",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "留言内容",
    "cta.messagePlaceholder": "告诉我们您的项目详情...",
    "cta.submit": "发送消息",
    "cta.success": "消息发送成功！",
    "cta.successMessage": "我们将很快与您联系。谢谢！",
    
    // Footer
    "footer.description": "为您的企业增长提供创新IT解决方案。数字营销、金融科技开发和电子商务领域的专业服务。",
    "footer.quickLinks": "快速链接",
    "footer.services": "服务项目",
    "footer.marketing": "数字营销",
    "footer.seo": "本地SEO优化",
    "footer.fintech": "金融科技开发",
    "footer.ecommerce": "电子商务解决方案",
    "footer.online": "在线商务",
    "footer.copyright": "Automatic Technology Solutions。保留所有权利。",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
  },
  tur: {
    // Header
    "header.home": "Ana Sayfa",
    "header.about": "Hakkımızda",
    "header.partners": "Ortaklarımız",
    "header.services": "Hizmetlerimiz",
    "header.results": "Sonuçlarımız",
    "header.contact": "İletişim",
    "header.start": "Projeye Başla",
    
    // About
    "about.badge": "Hakkımızda",
    "about.title": "Profesyonel BT Çözümleri ile Güvenilir Ortak",
    "about.subtitle": "Biz ATS - Automatic Technology Solutions - modern dijital çözümler oluşturma konusunda uzmanlaşmış bir şirketiz. Amacımız, yeni teknolojiler aracılığıyla müşterilerimizin işlerini geliştirmektir.",
    
    // Partners
    "partners.badge": "Ortaklarımız",
    "partners.title": "Dünya Çapında Çalışıyoruz",
    "partners.subtitle": "Bölgesel ve uluslararası ortaklarla işbirliği yapıyoruz. Her proje yerel özellikleri ve küresel standartları dikkate alır.",
    
    // Hero
    "hero.badge": "İnovasyon ve Büyüme",
    "hero.title": "İşiniz İçin Yenilikçi BT Çözümleri",
    "hero.titleHighlight": "Büyüme",
    "hero.titleEnd": "",
    "hero.subtitle": "Dijital pazarlama, fintech geliştirme ve e-ticaret çözümleriyle işinizi bir üst seviyeye taşıyoruz. Profesyonellik ve inovasyonun mükemmel birleşimi.",
    "hero.consultation": "Ücretsiz Danışmanlık Alın",
    "hero.viewServices": "Hizmetlerimizi İnceleyin",
    "hero.clients": "Müşteri",
    "hero.experience": "Yıllık Deneyim",
    "hero.support": "Teknik Destek",
    "hero.impressions": "Gösterim",
    "hero.engagement": "Etkileşim Oranı",
    "hero.coverage": "Erişim",
    "hero.buyers": "Online Alıcı",
    "hero.growth": "+20% Büyüme",
    "hero.highResult": "Yüksek Performans",
    "hero.wideAudience": "Geniş Kitle",
    "hero.digitalMarket": "Dijital Pazar",
    
    // Services
    "services.badge": "Hizmetlerimiz",
    "services.title": "İşiniz İçin Eksiksiz Dijital Çözümler",
    "services.subtitle": "Küçük ve orta ölçekli işletmeler için profesyonel hizmetler. Pazarlama, e-ticaret ve fintech alanında modern çözümler.",
    "services.marketing.title": "Dijital Pazarlama",
    "services.marketing.desc": "Sosyal medya analitiği, erişim genişletme ve hedef kitle etkileşimi. 2,86 milyona kadar kullanıcıya erişim sağlayın.",
    "services.seo.title": "Yerel SEO",
    "services.seo.desc": "Yerel bölgenizdeki müşterileri çekin. Küçük işletmeler için yerel arama sonuçlarında yüksek sıralamalar garantiliyoruz.",
    "services.fintech.title": "Fintech Geliştirme",
    "services.fintech.desc": "Finansal planlama için modern mobil uygulamalar. Hesapları ve bakiyeleri tek tıkla yönetin.",
    "services.ecommerce.title": "E-Ticaret Çözümleri",
    "services.ecommerce.desc": "Online mağazalar için mobil uygulamalar ve web platformları. Tam işlevsel ve kullanıcı dostu arayüzler.",
    "services.online.title": "Online Ticaret",
    "services.online.desc": "Alıcıların %90'ı online alışveriş yapıyor. Yardımımızla dijital ticarette öne çıkın ve satışlarınızı artırın.",
    "services.other.title": "Diğer Hizmetler",
    "services.other.desc": "Proje ihtiyaçlarınıza uygun özel çözümler geliştiriyoruz. Hemen iletişime geçin!",
    "services.other.button": "Bize Ulaşın",
    "services.detail": "Daha Fazla Bilgi",
    
    // Why Us
    "whyus.badge": "Neden Bizi Seçmelisiniz?",
    "whyus.title": "İşinizin Başarısı İçin Güvenilir Ortağınız",
    "whyus.desc1": "Sadece hizmet sunmuyoruz - başarınızda ortağınız oluyoruz. En son teknolojilerle birleştirilmiş her projeye özel yaklaşım.",
    "whyus.desc2": "5 yıldan fazla deneyim, 100'den fazla memnun müşteri ve binlerce başarılı proje - bu profesyonelliğimizin kanıtıdır.",
    "whyus.projects": "Tamamlanan Proje",
    "whyus.satisfaction": "Müşteri Memnuniyeti",
    "whyus.quality.title": "Premium Kalite",
    "whyus.quality.desc": "Her proje, endüstrinin en yüksek standartlarına göre profesyonel düzeyde gerçekleştirilir.",
    "whyus.targeted.title": "Hedefe Odaklı",
    "whyus.targeted.desc": "İş hedeflerinizi anlıyor ve bunlara etkili bir şekilde ulaşmanıza yardımcı oluyoruz.",
    "whyus.fast.title": "Hızlı Teslimat",
    "whyus.fast.desc": "Projeleri kaliteden ödün vermeden zamanında ve verimli bir şekilde teslim ediyoruz.",
    "whyus.reliable.title": "Güvenilirlik",
    "whyus.reliable.desc": "Verilerinizin güvenliği ve gizliliği bizim en önemli önceliğimizdir.",
    "whyus.team.title": "Uzman Ekip",
    "whyus.team.desc": "Deneyimli profesyonellerden oluşan ekip her zaman hizmetinizde.",
    "whyus.support.title": "7/24 Destek",
    "whyus.support.desc": "Kesintisiz destek ve hızlı yanıt süreleri garantisi.",
    
    // Portfolio
    "portfolio.badge": "Portfolyomuz",
    "portfolio.title": "Başarılı Proje Portföyü",
    "portfolio.subtitle": "Müşterilerimizle işbirliği içinde oluşturulmuş olağanüstü projeler. Her birinin kendine özgü bir başarı hikayesi var.",
    "portfolio.button": "Bizimle Projenize Başlayın",
    "portfolio.project1.title": "Pazarlama Platformu",
    "portfolio.project1.category": "Dijital Pazarlama",
    "portfolio.project1.description": "Sosyal medya analizi ve yönetim sistemi. %300 erişim artışı.",
    "portfolio.project1.stats": "2.5M+ Kullanıcı",
    "portfolio.project2.title": "Fintech Uygulaması",
    "portfolio.project2.category": "Fintech",
    "portfolio.project2.description": "Finansal yönetim ve planlama için mobil uygulama. Banka seviyesinde güvenlik.",
    "portfolio.project2.stats": "500K+ İndirme",
    "portfolio.project3.title": "E-Ticaret Mağazası",
    "portfolio.project3.category": "E-Ticaret",
    "portfolio.project3.description": "Tam işlevsel online mağaza. %200 satış artışı ve dönüşüm iyileştirmesi.",
    "portfolio.project3.stats": "$1M+ Satış",
    "portfolio.project4.title": "Startup Ekosistemi",
    "portfolio.project4.category": "B2B Platform",
    "portfolio.project4.description": "Startup'lar için karmaşık yönetim sistemi. Ekip işbirliği ve analitik.",
    "portfolio.project4.stats": "100+ Şirket",
    "portfolio.project5.title": "CRM Sistemi",
    "portfolio.project5.category": "Kurumsal",
    "portfolio.project5.description": "Müşteri ilişkileri yönetimi için güçlü araç. AI entegrasyonu.",
    "portfolio.project5.stats": "10K+ Kullanıcı",
    "portfolio.project6.title": "Analitik Platformu",
    "portfolio.project6.category": "Analitik",
    "portfolio.project6.description": "Gerçek zamanlı iş analizi ve tahmin sistemi. Veri odaklı kararlar.",
    "portfolio.project6.stats": "50TB+ Veri",
    
    // Stats
    "stats.badge": "Sonuçlarımız",
    "stats.title": "Rakamlar Kendi Kendine Konuşuyor",
    "stats.subtitle": "Müşterilerimiz için elde edilen başarılar. Profesyonel yaklaşım ve modern teknolojilerin sonucu.",
    "stats.growth": "Son 6 Aydaki Büyüme",
    "stats.clients": "Memnun Müşteri",
    
    // Testimonials
    "testimonials.badge": "Müşteri Görüşleri",
    "testimonials.title": "Müşterilerimiz Hakkımızda Ne Diyor",
    "testimonials.subtitle": "En büyük gururumuz memnun müşterilerimizdir. Görüşleri kalitemizin en iyi kanıtıdır.",
    "testimonials.rating": "Ortalama Puan",
    "testimonials.reviews": "Değerlendirme",
    "testimonials.recommend": "Tavsiye Eder",
    "testimonials.years": "Yıllık Deneyim",
    "testimonials.testimonial1.name": "Jamshid Abdullayev",
    "testimonials.testimonial1.position": "Genel Müdür",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "ATS ekibiyle çalışmak harika bir deneyimdi. İşimizi gerçekten anladılar ve mükemmel bir çözüm yarattılar. Satışlarımız %200 arttı!",
    "testimonials.testimonial2.name": "Dilnoza Karimova",
    "testimonials.testimonial2.position": "Pazarlama Direktörü",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "Profesyonel yaklaşım, modern teknolojiler ve mükemmel sonuçlar. Pazarlama kampanyamız rakiplerden çok ileride. Kesinlikle tavsiye ederim!",
    "testimonials.testimonial3.name": "Rustam Yusupov",
    "testimonials.testimonial3.position": "Kurucu",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "Fintech uygulamamızı geliştirirken ATS ile işbirliğinden çok memnunuz. Fikirlerimizi mükemmel bir uygulamaya dönüştürdüler. Gerçek profesyoneller!",
    "testimonials.testimonial4.name": "Nodira Rahimova",
    "testimonials.testimonial4.position": "Sahip",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "E-ticaret platformumuz için mükemmel iş çıkardılar. Site hızlı çalışıyor, güzel görünüyor ve müşteriler için çok kullanışlı. Hizmet birinci sınıf!",
    "testimonials.testimonial5.name": "Aziz Tursunov",
    "testimonials.testimonial5.position": "BT Müdürü",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "Yerel SEO hizmetleri bize çok sayıda yeni müşteri getirdi. Arama sonuçlarında birinci sıradayız. ATS güvenilir bir ortak!",
    "testimonials.testimonial6.name": "Shoxrux Mamadov",
    "testimonials.testimonial6.position": "Genel Müdür",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "CRM sistemimizi yönetmek hiç bu kadar kolay olmamıştı. ATS ekibi tüm gereksinimlerimizi dikkate aldı. Mükemmel sonuç!",
    
    // CTA
    "cta.badge": "İletişime Geçin",
    "cta.title": "Projenizi Bugün Başlatın",
    "cta.subtitle": "İşinizi bir üst seviyeye taşımaya hazır mısınız? Şimdi bizimle iletişime geçin ve ücretsiz danışmanlık alın.",
    "cta.email": "E-posta",
    "cta.phone": "Telefon",
    "cta.address": "Adres",
    "cta.addressValue": "Taşkent, Özbekistan",
    "cta.name": "Adınız",
    "cta.namePlaceholder": "Adınızı girin",
    "cta.emailLabel": "E-posta Adresiniz",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "Mesajınız",
    "cta.messagePlaceholder": "Projeniz hakkında bize bilgi verin...",
    "cta.submit": "Mesaj Gönder",
    "cta.success": "Mesaj Başarıyla Gönderildi!",
    "cta.successMessage": "Kısa süre içinde sizinle iletişime geçeceğiz. Teşekkürler!",
    
    // Footer
    "footer.description": "İş büyümeniz için yenilikçi BT çözümleri. Dijital pazarlama, fintech geliştirme ve e-ticaret alanında profesyonel hizmetler.",
    "footer.quickLinks": "Hızlı Bağlantılar",
    "footer.services": "Hizmetler",
    "footer.marketing": "Dijital Pazarlama",
    "footer.seo": "Yerel SEO",
    "footer.fintech": "Fintech Geliştirme",
    "footer.ecommerce": "E-Ticaret Çözümleri",
    "footer.online": "Online Ticaret",
    "footer.copyright": "Automatic Technology Solutions. Tüm hakları saklıdır.",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Hizmet Şartları",
  },
  deu: {
    // Header
    "header.home": "Startseite",
    "header.about": "Über uns",
    "header.partners": "Unsere Partner",
    "header.services": "Dienstleistungen",
    "header.results": "Ergebnisse",
    "header.contact": "Kontakt",
    "header.start": "Projekt starten",
    
    // About
    "about.badge": "Über uns",
    "about.title": "Zuverlässiger Partner mit professionellen IT-Lösungen",
    "about.subtitle": "Wir sind ATS - Automatic Technology Solutions - ein Unternehmen, das sich auf die Erstellung moderner digitaler Lösungen spezialisiert hat. Unser Ziel ist es, das Geschäft unserer Kunden durch neue Technologien zu entwickeln.",
    
    // Partners
    "partners.badge": "Unsere Partner",
    "partners.title": "Wir arbeiten weltweit",
    "partners.subtitle": "Wir arbeiten mit regionalen und internationalen Partnern zusammen. Jedes Projekt berücksichtigt lokale Besonderheiten und globale Standards.",
    
    // Hero
    "hero.badge": "Innovation und Wachstum",
    "hero.title": "Innovative IT-Lösungen für Ihr Unternehmen",
    "hero.titleHighlight": "Wachstum",
    "hero.titleEnd": "",
    "hero.subtitle": "Wir bringen Ihr Unternehmen durch digitales Marketing, Fintech-Entwicklung und E-Commerce-Lösungen auf die nächste Stufe. Eine perfekte Kombination aus Professionalität und Innovation.",
    "hero.consultation": "Kostenlose Beratung erhalten",
    "hero.viewServices": "Unsere Dienstleistungen ansehen",
    "hero.clients": "Kunden",
    "hero.experience": "Jahre Erfahrung",
    "hero.support": "Technischer Support",
    "hero.impressions": "Impressionen",
    "hero.engagement": "Engagement-Rate",
    "hero.coverage": "Reichweite",
    "hero.buyers": "Online-Käufer",
    "hero.growth": "+20% Wachstum",
    "hero.highResult": "Hohe Leistung",
    "hero.wideAudience": "Breites Publikum",
    "hero.digitalMarket": "Digitaler Markt",
    
    // Services
    "services.badge": "Unsere Dienstleistungen",
    "services.title": "Vollständige Digitale Lösungen für Ihr Unternehmen",
    "services.subtitle": "Professionelle Dienstleistungen für kleine und mittelständische Unternehmen. Moderne Lösungen in den Bereichen Marketing, E-Commerce und Fintech.",
    "services.marketing.title": "Digitales Marketing",
    "services.marketing.desc": "Social-Media-Analyse, Reichweitenerweiterung und Zielgruppen-Engagement. Erreichen Sie bis zu 2,86 Millionen Nutzer.",
    "services.seo.title": "Lokales SEO",
    "services.seo.desc": "Gewinnen Sie Kunden aus Ihrer Region. Wir garantieren hohe Rankings in lokalen Suchergebnissen für kleine Unternehmen.",
    "services.fintech.title": "Fintech-Entwicklung",
    "services.fintech.desc": "Moderne mobile Anwendungen für Finanzplanung. Verwalten Sie Konten und Guthaben mit einem einzigen Klick.",
    "services.ecommerce.title": "E-Commerce-Lösungen",
    "services.ecommerce.desc": "Mobile Apps und Webplattformen für Online-Shops. Voll funktionsfähige und benutzerfreundliche Oberflächen.",
    "services.online.title": "Online-Handel",
    "services.online.desc": "90% der Käufer kaufen online. Heben Sie sich mit unserer Hilfe im digitalen Handel ab und steigern Sie Ihre Verkäufe.",
    "services.other.title": "Weitere Dienstleistungen",
    "services.other.desc": "Wir entwickeln maßgeschneiderte Lösungen für Ihre Projektanforderungen. Kontaktieren Sie uns noch heute!",
    "services.other.button": "Kontaktieren Sie uns",
    "services.detail": "Mehr erfahren",
    
    // Why Us
    "whyus.badge": "Warum uns wählen?",
    "whyus.title": "Ihr zuverlässiger Partner für Unternehmenserfolg",
    "whyus.desc1": "Wir bieten nicht nur Dienstleistungen an - wir werden Ihr Partner für den Erfolg. Individueller Ansatz für jedes Projekt kombiniert mit modernsten Technologien.",
    "whyus.desc2": "Über 5 Jahre Erfahrung, mehr als 100 zufriedene Kunden und Tausende erfolgreiche Projekte - das ist der Beweis für unsere Professionalität.",
    "whyus.projects": "Abgeschlossene Projekte",
    "whyus.satisfaction": "Kundenzufriedenheit",
    "whyus.quality.title": "Premium-Qualität",
    "whyus.quality.desc": "Jedes Projekt wird auf professionellem Niveau nach den höchsten Industriestandards durchgeführt.",
    "whyus.targeted.title": "Zielorientiert",
    "whyus.targeted.desc": "Wir verstehen Ihre Geschäftsziele und helfen Ihnen effektiv, diese zu erreichen.",
    "whyus.fast.title": "Schnelle Lieferung",
    "whyus.fast.desc": "Wir liefern Projekte pünktlich und effizient, ohne Kompromisse bei der Qualität einzugehen.",
    "whyus.reliable.title": "Zuverlässigkeit",
    "whyus.reliable.desc": "Die Sicherheit und Vertraulichkeit Ihrer Daten hat für uns höchste Priorität.",
    "whyus.team.title": "Expertenteam",
    "whyus.team.desc": "Ein Team erfahrener Profis steht Ihnen jederzeit zur Verfügung.",
    "whyus.support.title": "24/7 Support",
    "whyus.support.desc": "Garantiert kontinuierlicher Support und schnelle Reaktionszeiten.",
    
    // Portfolio
    "portfolio.badge": "Unser Portfolio",
    "portfolio.title": "Portfolio erfolgreicher Projekte",
    "portfolio.subtitle": "Herausragende Projekte, die in Zusammenarbeit mit unseren Kunden entstanden sind. Jedes hat seine eigene einzigartige Erfolgsgeschichte.",
    "portfolio.button": "Starten Sie Ihr Projekt mit uns",
    "portfolio.project1.title": "Marketing-Plattform",
    "portfolio.project1.category": "Digitales Marketing",
    "portfolio.project1.description": "Social-Media-Analyse- und Verwaltungssystem. 300% Reichweitensteigerung.",
    "portfolio.project1.stats": "2,5M+ Nutzer",
    "portfolio.project2.title": "Fintech-Anwendung",
    "portfolio.project2.category": "Fintech",
    "portfolio.project2.description": "Mobile App für Finanzverwaltung und -planung. Sicherheit auf Bankniveau.",
    "portfolio.project2.stats": "500K+ Downloads",
    "portfolio.project3.title": "E-Commerce-Shop",
    "portfolio.project3.category": "E-Commerce",
    "portfolio.project3.description": "Voll funktionsfähiger Online-Shop. 200% Umsatzsteigerung und verbesserte Konversion.",
    "portfolio.project3.stats": "$1M+ Umsatz",
    "portfolio.project4.title": "Startup-Ökosystem",
    "portfolio.project4.category": "B2B-Plattform",
    "portfolio.project4.description": "Komplexes Verwaltungssystem für Startups. Teamzusammenarbeit und Analytik.",
    "portfolio.project4.stats": "100+ Unternehmen",
    "portfolio.project5.title": "CRM-System",
    "portfolio.project5.category": "Enterprise",
    "portfolio.project5.description": "Leistungsstarkes Tool für Kundenbeziehungsmanagement. KI-Integration.",
    "portfolio.project5.stats": "10K+ Nutzer",
    "portfolio.project6.title": "Analyse-Plattform",
    "portfolio.project6.category": "Analytik",
    "portfolio.project6.description": "Echtzeit-Geschäftsanalyse- und Prognosesystem. Datengestützte Entscheidungen.",
    "portfolio.project6.stats": "50TB+ Daten",
    
    // Stats
    "stats.badge": "Unsere Ergebnisse",
    "stats.title": "Zahlen sprechen für sich",
    "stats.subtitle": "Für unsere Kunden erzielte Erfolge. Das Ergebnis professioneller Herangehensweise und moderner Technologien.",
    "stats.growth": "Wachstum in den letzten 6 Monaten",
    "stats.clients": "Zufriedene Kunden",
    
    // Testimonials
    "testimonials.badge": "Kundenmeinungen",
    "testimonials.title": "Was unsere Kunden über uns sagen",
    "testimonials.subtitle": "Unser größter Stolz sind unsere zufriedenen Kunden. Ihre Aussagen sind der beste Beweis für unsere Qualität.",
    "testimonials.rating": "Durchschnittliche Bewertung",
    "testimonials.reviews": "Bewertungen",
    "testimonials.recommend": "Würden uns empfehlen",
    "testimonials.years": "Jahre Erfahrung",
    "testimonials.testimonial1.name": "Jamshid Abdullayev",
    "testimonials.testimonial1.position": "Geschäftsführer",
    "testimonials.testimonial1.company": "Digital Store",
    "testimonials.testimonial1.text": "Die Zusammenarbeit mit dem ATS-Team war eine großartige Erfahrung. Sie haben unser Geschäft wirklich verstanden und die perfekte Lösung geschaffen. Unser Umsatz ist um 200% gestiegen!",
    "testimonials.testimonial2.name": "Dilnoza Karimova",
    "testimonials.testimonial2.position": "Marketing-Direktorin",
    "testimonials.testimonial2.company": "Fashion Hub",
    "testimonials.testimonial2.text": "Professioneller Ansatz, moderne Technologien und hervorragende Ergebnisse. Unsere Marketingkampagne liegt weit vor der Konkurrenz. Definitiv empfehlenswert!",
    "testimonials.testimonial3.name": "Rustam Yusupov",
    "testimonials.testimonial3.position": "Gründer",
    "testimonials.testimonial3.company": "StartUp Tashkent",
    "testimonials.testimonial3.text": "Wir sind sehr zufrieden mit unserer Zusammenarbeit mit ATS bei der Entwicklung unserer Fintech-App. Sie haben unsere Ideen in eine hervorragende Anwendung verwandelt. Echte Profis!",
    "testimonials.testimonial4.name": "Nodira Rahimova",
    "testimonials.testimonial4.position": "Inhaberin",
    "testimonials.testimonial4.company": "BeautyShop UZ",
    "testimonials.testimonial4.text": "Sie haben hervorragende Arbeit für unsere E-Commerce-Plattform geleistet. Die Website läuft schnell, sieht toll aus und ist sehr benutzerfreundlich. Service erstklassig!",
    "testimonials.testimonial5.name": "Aziz Tursunov",
    "testimonials.testimonial5.position": "IT-Manager",
    "testimonials.testimonial5.company": "Global Trade",
    "testimonials.testimonial5.text": "Lokale SEO-Dienstleistungen haben uns viele neue Kunden gebracht. Wir sind an erster Stelle in den Suchergebnissen. ATS ist ein zuverlässiger Partner!",
    "testimonials.testimonial6.name": "Shoxrux Mamadov",
    "testimonials.testimonial6.position": "Geschäftsführer",
    "testimonials.testimonial6.company": "Tech Innovations",
    "testimonials.testimonial6.text": "Die Verwaltung unseres CRM-Systems war noch nie so einfach. Das ATS-Team hat alle unsere Anforderungen berücksichtigt. Hervorragendes Ergebnis!",
    
    // CTA
    "cta.badge": "Kontakt aufnehmen",
    "cta.title": "Starten Sie Ihr Projekt heute",
    "cta.subtitle": "Bereit, Ihr Unternehmen auf die nächste Stufe zu bringen? Kontaktieren Sie uns jetzt und erhalten Sie eine kostenlose Beratung.",
    "cta.email": "E-Mail",
    "cta.phone": "Telefon",
    "cta.address": "Adresse",
    "cta.addressValue": "Taschkent, Usbekistan",
    "cta.name": "Ihr Name",
    "cta.namePlaceholder": "Geben Sie Ihren Namen ein",
    "cta.emailLabel": "Ihre E-Mail",
    "cta.emailPlaceholder": "email@example.com",
    "cta.message": "Nachricht",
    "cta.messagePlaceholder": "Erzählen Sie uns von Ihrem Projekt...",
    "cta.submit": "Nachricht senden",
    "cta.success": "Nachricht erfolgreich gesendet!",
    "cta.successMessage": "Wir werden uns in Kürze bei Ihnen melden. Vielen Dank!",
    
    // Footer
    "footer.description": "Innovative IT-Lösungen für Ihr Unternehmenswachstum. Professionelle Dienstleistungen in den Bereichen digitales Marketing, Fintech-Entwicklung und E-Commerce.",
    "footer.quickLinks": "Schnelllinks",
    "footer.services": "Dienstleistungen",
    "footer.marketing": "Digitales Marketing",
    "footer.seo": "Lokales SEO",
    "footer.fintech": "Fintech-Entwicklung",
    "footer.ecommerce": "E-Commerce-Lösungen",
    "footer.online": "Online-Handel",
    "footer.copyright": "Automatic Technology Solutions. Alle Rechte vorbehalten.",
    "footer.privacy": "Datenschutzerklärung",
    "footer.terms": "Nutzungsbedingungen",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("uzb");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
